services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: riselab3d
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  backend:
    build:
      context: ./backend
    ports:
      - '4000:4000'
    environment:
      DATABASE_URL: postgres://postgres:prisma@db:5432/riselab3d
      PORT: 4000
    depends_on:
      - db
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules

  frontend:
    build:
      context: ./frontend
    ports:
      - '5173:5173'
    environment:
      VITE_API_PROXY_TARGET: http://backend:4000
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  db-data:
