/**
 * Mock Data Layer
 * Simulação de dados para desenvolvimento sem PostgreSQL
 * Usado quando o banco não está disponível
 */

export const mockData = {
  tenant1: {
    productColors: [
      { id: 'product_color_black', name: 'Preto' },
      { id: 'product_color_white', name: 'Branco' },
      { id: 'product_color_gray', name: 'Cinza' },
      { id: 'product_color_red', name: 'Vermelho' },
      { id: 'product_color_blue', name: 'Azul' },
      { id: 'product_color_green', name: 'Verde' },
      { id: 'product_color_yellow', name: 'Amarelo' },
      { id: 'product_color_orange', name: 'Laranja' },
      { id: 'product_color_purple', name: 'Roxo' },
      { id: 'product_color_pink', name: 'Rosa' },
      { id: 'product_color_brown', name: 'Marrom' },
      { id: 'product_color_beige', name: 'Bege' },
      { id: 'product_color_transparent', name: 'Transparente' },
    ],
    printerModels: [
      { id: 'printer_model_a1', name: 'A1', consumoWattsPadrao: 120, vidaUtilHorasPadrao: 2000, createdAt: new Date('2026-04-01T00:00:00.000Z'), updatedAt: new Date('2026-04-01T00:00:00.000Z') },
      { id: 'printer_model_a1_mini', name: 'A1 Mini', consumoWattsPadrao: 95, vidaUtilHorasPadrao: 1800, createdAt: new Date('2026-04-01T00:00:00.000Z'), updatedAt: new Date('2026-04-01T00:00:00.000Z') },
      { id: 'printer_model_p1s', name: 'P1S', consumoWattsPadrao: 350, vidaUtilHorasPadrao: 2500, createdAt: new Date('2026-04-01T00:00:00.000Z'), updatedAt: new Date('2026-04-01T00:00:00.000Z') },
      { id: 'printer_model_p2s', name: 'P2S', consumoWattsPadrao: 420, vidaUtilHorasPadrao: 3000, createdAt: new Date('2026-04-01T00:00:00.000Z'), updatedAt: new Date('2026-04-01T00:00:00.000Z') },
      { id: 'printer_model_x1c', name: 'X1 Carbon', consumoWattsPadrao: 360, vidaUtilHorasPadrao: 2800, createdAt: new Date('2026-04-01T00:00:00.000Z'), updatedAt: new Date('2026-04-01T00:00:00.000Z') },
      { id: 'printer_model_k1_max', name: 'K1 Max', consumoWattsPadrao: 350, vidaUtilHorasPadrao: 2500, createdAt: new Date('2026-04-01T00:00:00.000Z'), updatedAt: new Date('2026-04-01T00:00:00.000Z') },
      { id: 'printer_model_ender3v3', name: 'Ender 3 V3', consumoWattsPadrao: 120, vidaUtilHorasPadrao: 2000, createdAt: new Date('2026-04-01T00:00:00.000Z'), updatedAt: new Date('2026-04-01T00:00:00.000Z') },
    ],
    printers: [
      {
        id: 'printer_1',
        tenantId: 'tenant_1',
        nome: 'Ender 3 Pro',
        modelId: 'printer_model_ender3v3',
        model: {
          id: 'printer_model_ender3v3',
          name: 'Ender 3 V3',
          consumoWattsPadrao: 120,
          vidaUtilHorasPadrao: 2000,
          createdAt: new Date('2026-04-01T00:00:00.000Z'),
          updatedAt: new Date('2026-04-01T00:00:00.000Z'),
        },
        consumo_watts: 120,
        custo_aquisicao: 1500,
        vida_util_horas: 2000,
        data_desativacao: null,
      },
      {
        id: 'printer_2',
        tenantId: 'tenant_1',
        nome: 'Creality Ender 5',
        modelId: 'printer_model_k1_max',
        model: {
          id: 'printer_model_k1_max',
          name: 'K1 Max',
          consumoWattsPadrao: 350,
          vidaUtilHorasPadrao: 2500,
          createdAt: new Date('2026-04-01T00:00:00.000Z'),
          updatedAt: new Date('2026-04-01T00:00:00.000Z'),
        },
        consumo_watts: 150,
        custo_aquisicao: 2000,
        vida_util_horas: 2500,
        data_desativacao: null,
      },
    ],
    filaments: [
      {
        id: 'filament_1',
        tenantId: 'tenant_1',
        marca: 'Prusa',
        lote: 'L001',
        data_compra: new Date('2026-04-01T00:00:00.000Z'),
        tipo: 'PLA',
        custo_por_kg: 120,
        data_desativacao: null,
      },
      {
        id: 'filament_2',
        tenantId: 'tenant_1',
        marca: 'Prusament',
        lote: 'P2026-02',
        data_compra: new Date('2026-04-12T00:00:00.000Z'),
        tipo: 'PETG',
        custo_por_kg: 150,
        data_desativacao: null,
      },
    ],
    settings: {
      id: 'settings_1',
      tenantId: 'tenant_1',
      custo_kwh: 1.05,
      margem_venda_direta: 20,
      margem_venda_ecommerce: 35,
      margem_venda_consumidor_final: 50,
      logo_data_url: null,
    },
    products: [
      {
        id: 'prod_1',
        tenantId: 'tenant_1',
        nome: 'Suporte',
        cor: 'Preto',
        variacao: 'P',
        sku: 'SuportePretoP',
        peso_gramas: 50,
        tempo_impressao_horas: 1.5,
        custo_material: 6.0,
        custo_energia: 0,
        custo_amortizacao: 0,
        custo_adicional: 0,
        falha_percentual: 10,
        custo_total: 6.6,
        printerId: null,
        filamentId: 'filament_1',
        data_desativacao: null,
        printer: null,
        filament: {
          id: 'filament_1',
          tenantId: 'tenant_1',
          marca: 'Prusa',
          lote: 'L001',
          data_compra: new Date('2026-04-01T00:00:00.000Z'),
          tipo: 'PLA',
          custo_por_kg: 120,
          data_desativacao: null,
        },
      },
      {
        id: 'prod_2',
        tenantId: 'tenant_1',
        nome: 'Encaixe',
        cor: 'Azul',
        variacao: 'M',
        sku: 'EncaixeAzulM',
        peso_gramas: 75,
        tempo_impressao_horas: 2.0,
        custo_material: 9.0,
        custo_energia: 0,
        custo_amortizacao: 0,
        custo_adicional: 0,
        falha_percentual: 10,
        custo_total: 9.9,
        printerId: null,
        filamentId: 'filament_2',
        data_desativacao: null,
        printer: null,
        filament: {
          id: 'filament_2',
          tenantId: 'tenant_1',
          marca: 'Prusament',
          lote: 'P2026-02',
          data_compra: new Date('2026-04-12T00:00:00.000Z'),
          tipo: 'PETG',
          custo_por_kg: 150,
          data_desativacao: null,
        },
      },
    ],
    feedbacks: [
      {
        id: 'feedback_1',
        tenantId: 'tenant_1',
        userId: 'user_admin',
        category: 'Nova funcionalidade',
        subject: 'Sugestão de automação comercial',
        message: 'Seria útil ter um fluxo mais rápido para duplicar orçamentos recorrentes.',
        status: 'novo',
        createdAt: new Date('2026-04-18T12:00:00.000Z'),
      },
    ],
    quotes: [],
  },
};
